### PR TITLE
add: `softmaker-freeoffice-2024-deb`

### PR DESCRIPTION
**Pull request by erenfro**
Proprietary office suite; word processing, spreadsheets, presentations; limited feature free edition

### CODE REVIEW

**Comment by erenfro** [comment]
Funny, the one test that failed, just failed to download the original deb, but all the others succeeded without issue... That should be a simple re-test or such.

**Comment by erenfro** [comment]
Currently working on replaces/conflicts between softmaker-office-2024, softmaker-office-nx and softmaker-freeoffice-2024

**Comment by erenfro** [comment]
This is now ready for review.

**Comment by Elsie19** [comment]
Too many things are failing. Disable them with `incompatible`.

**Comment by Xdavius** [comment]
> This is now ready for review.

Hi. I have added some comments. Please, give it a look and apply for the 3 packages if it's OK for at least 1.

**Review by oklopfer — APPROVED** [review]

**Pull request merged**
