### PR TITLE
upd(maitreya-deb): `8.0.1b` -> `8.1`

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Review by Elsie19 — CHANGES_REQUESTED** [review]
fails to remove.

**Comment by Zahrun** [comment]
@Elsie19 will the change of `gives` change the name in repology? cf. https://github.com/pacstall/pacstall-programs/pull/3765

**Comment by Elsie19** [comment]
Not that I know of.

**Comment by Zahrun** [comment]
Ok this deb works only in jammy but it should be good to merge now

**Review by Elsie19 — APPROVED** [review]

**Pull request merged**
