### PR TITLE
add: `hypnotix-deb`

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Comment by Zahrun** [comment]
` hypnotix : Depends: python3-imdbpy but it is not installable`
But the package seems available in debian repos https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python3-imdbpy

**Comment by Henryws** [comment]
Is it available in debian testing?

**Comment by Zahrun** [comment]
> Is it available in debian testing?

It is not for some reason. I’ll create a pacscript for that dependency then

**Comment by Zahrun** [comment]
Requires https://github.com/pacstall/pacstall-programs/pull/1834

**Review by Henryws — CHANGES_REQUESTED** [review]
Add `hash` for each version.

**Review by Henryws — APPROVED** [review]

**Pull request merged**
