### PR TITLE
add: `github-cli-git`

### PR DESCRIPTION
**Pull request by WRM-42**

### CODE REVIEW

**Comment by Henryws** [comment]
Add `go` to deps list

**Comment by WRM-42** [comment]
It's already there:

`pacdeps=("go-bin")
`

**Comment by Henryws** [comment]
Seems to be a bug with pacdeps in the develop branch, gonna manually test on master.

**Comment by Henryws** [comment]
image
@saenai255 issue with `go-bin`

**Comment by Henryws** [comment]
@WRM-42 Can you test by running the following commands, then screenshotting:
```bash
pacstall -U Henryws fix-pacdeps-again
pacstall -I $your_scripts
# screenshot them, upload them here
pacstall -U pacstall master # if you want to go back to the master branch
```

**Comment by WRM-42** [comment]
Pacdep now works correctly, looks like an issue with Go
ubuntu_HclNvkywCW
ubuntu_Ddqqy5ft4E

**Comment by Mar0xy** [comment]
I guess the go issue has to do with the fact that the root has to be changed as an env variable which is done by the pacstall script but you also need to source/update the current environment to have the change be applied which doesn't obviously happen in this case causing it to break.

**Comment by Henryws** [comment]
So what should we do?

**Comment by cat-master21** [comment]
Maybe perhaps instead use distribution's golang-go: https://packages.ubuntu.com/jammy/golang-go

**Pull request closed without merging**
