### PR TITLE
fix(tenacity-git): add missing build dependencies

### PR DESCRIPTION
**Pull request by echometerain**
#765

### CODE REVIEW

**Review by Henryws — DISMISSED** [review]

**Review by Henryws — DISMISSED** [review]

**Comment by wizard-28** [comment]
@echometerain `wxWidgets` not found.

**Review by Henryws — CHANGES_REQUESTED** [review]
Check CI logs

**Review by wizard-28 — APPROVED** [review]
Looks good

**Review by Henryws — APPROVED** [review]
works on my machine

**Pull request merged**
