### PR TITLE
upd(spotify-client-deb): `1.2.26` -> `1.2.31`

### PR DESCRIPTION
**Pull request by FunkyEgg**
Fixed .deb not being reachable

### CODE REVIEW

**Comment by Elsie19** [comment]
Fix the amount of backticks.

**Comment by FunkyEgg** [comment]
Sorry about that, thought you needed 3

**Comment by Elsie19** [comment]
Nope! Just 1 level. Where'd you read 3?

**Comment by FunkyEgg** [comment]
I'm use to doing code blocks on discord where you use 3, I don't really use online stuff, good to know though

**Review by Elsie19 — APPROVED** [review]

**Pull request merged**
