### PR TITLE
ci(tests): fix TZ data

### PR DESCRIPTION
**Pull request by cat-master21**
Hopefully this should fix TimeZone error on some tests.

### CODE REVIEW

**Comment by wizard-28** [comment]
I need to test this workflow. Can you join our discord/matrix, so that you can start the workflow on your repository with debug mode enabled? This will print a SSH link in the CI logs, which I'll need to test it.

Discord: https://discord.com/invite/yzrjXJV6K8
Matrix: https://matrix.to/#/#pacstall:matrix.org

**Comment by cat-master21** [comment]
Right, so how do I do this? New to Matrix in general also.

**Comment by Henryws** [comment]
Do you need help on how to join matrix?

**Comment by wizard-28** [comment]
> Right, so how do I do this? New to Matrix in general also.

You can join the Discord if you're more comfortable with it. Just click the link in any case & the websites will guide you.

**Comment by cat-master21** [comment]
whops

**Comment by cat-master21** [comment]
Should be ready for merge now whenever. @wizard-28 my branch (patch-2) did succeed by the way later on.

**Comment by wizard-28** [comment]
> Good news, test ran installing element-desktop-deb from #729 which can now install on all distros on a test I ran: https://github.com/cat-master21/pacstall-programs/runs/5164045859?check_suite_focus=true.

`tzdata` isn't being installed as a dependency in your CI run, whereas it was trying to install it in ours (which resulted in the problem). Any idea why?

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
