### PR TITLE
add: `nu-tongues-bin`

### PR DESCRIPTION
**Pull request by wren54**
nu-tongues is a translation plugin for nushell used by the nu rhino-pkg

### CODE REVIEW

**Review by Elsie19 — CHANGES_REQUESTED** [review]
image

**Comment by oklopfer** [comment]
> image
Wut I don’t get this issue

**Comment by oklopfer** [comment]
Nvm I see it now but it seems to be working fine locally…

**Comment by Elsie19** [comment]
Same issue with the plugin loading.

**Comment by oklopfer** [comment]
Why was it working for me last night 😭😭

**Pull request merged**
