### PR TITLE
upd(lbry-deb): `0.52.0` -> `0.52.5`

### PR DESCRIPTION
**Pull request by cat-master21**

### CODE REVIEW

**Review by wizard-28 — APPROVED** [review]

**Review by wizard-28 — CHANGES_REQUESTED** [review]
@Madiator2011 isn't active on GitHub anymore, so @cat-master21 replace them as the maintainer.

**Comment by kodxana** [comment]
@wizard-28 sorry for being AFK to much stuff recently though now I'm back :)

**Comment by wizard-28** [comment]
So @kodxana do you wish to continue maintaining this pacscript?

**Comment by kodxana** [comment]
Yup

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
