### PR TITLE
upd(emacs): `28.2` -> `29.1`

### PR DESCRIPTION
**Pull request by vigress8**

### CODE REVIEW

**Review by Elsie19 — CHANGES_REQUESTED** [review]
Fails on everything except 2 Ubuntu runs.

**Comment by vigress8** [comment]
Dependency naming shenanigans again. Will look into it when I have time

**Review by Elsie19 — CHANGES_REQUESTED** [review]
What are we doing here with removing the config variables?

**Comment by vigress8** [comment]
That level of configuration makes more sense for `emacs-git`. Most users who type `pacstall -I emacs` most likely want to just install the latest stable release of Emacs, without all of that.
It also makes this script an unmaintainable clusterfuck, with dependencies scattered all over the place

**Pull request closed without merging**
