### PR TITLE
add: `paconvert-git`

### PR DESCRIPTION
**Pull request by cat-master21**
I'm surprised this wasn't added sooner!

### CODE REVIEW

**Comment by cat-master21** [comment]
Strange that git can't clone this as I can:
Screenshot

**Comment by cat-master21** [comment]
Also this fails only for dev branch: https://github.com/pacstall/pacstall-programs/runs/5545838933?check_suite_focus=true#step:9:27 develop branch vs https://github.com/pacstall/pacstall-programs/runs/5545838892?check_suite_focus=true#step:9:26 stable, on Ubuntu latest.

**Comment by Henryws** [comment]
Yes, we need to put http code 301 in the acceptable codes check

**Comment by wizard-28** [comment]
@Henryws will make a PR fixing that after his vacation (1 day remaining).

**Comment by wizard-28** [comment]
@Henryws check on this.

**Review by Henryws — APPROVED** [review]

**Pull request merged**
