### PR TITLE
[Update Package] Updated mutt-wizard to install license

### PR DESCRIPTION
**Pull request by JonBoyleCoding**

### CODE REVIEW

**Comment by JonBoyleCoding** [comment]
I'm not sure if there is some form of release version like in AUR as there hasn't been an update in actual program version, but a change in what gets installed.

**Review by wizard-28 — APPROVED** [review]
Approved, so should I merge?

**Comment by wizard-28** [comment]
> I'm not sure if there is some form of release version like in AUR as there hasn't been an update in actual program version, but a change in what gets installed.

You mean `pkgrel`? No it doesn't exist in pacstall

**Comment by JonBoyleCoding** [comment]
> > I'm not sure if there is some form of release version like in AUR as there hasn't been an update in actual program version, but a change in what gets installed.
> 
> You mean `pkgrel`? No it doesn't exist in pacstall

Indeed, that is what I meant.

**Comment by JonBoyleCoding** [comment]
> Approved, so should I merge?

If you're happy with it, I am.

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Never mind! The makefile already does this

**Review by wizard-28 — APPROVED** [review]
Merging

**Pull request merged**
