### PR TITLE
add: `wezterm`

### PR DESCRIPTION
**Pull request by smokeythemonkey**
## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [ ] Add maintainer to pacscript

### CODE REVIEW

**Comment by Henryws** [comment]
Fix the title.

**Comment by Henryws** [comment]
CI fails.

**Comment by smokeythemonkey** [comment]
They ran and passed in my fork. Tested in vm's too. Will re-run them again later.

**Comment by Henryws** [comment]
Did you test on Ubuntu rolling?

**Comment by smokeythemonkey** [comment]
made some changes, all Ubuntu tests run, Debian testing fails and unstable only passes with unstable develop... 
Not sure what else to do.

**Comment by smokeythemonkey** [comment]
Will drop this and focus on -app and -bin pacscripts for now

**Pull request closed without merging**
