### PR TITLE
add: `softmaker-office-nx-deb`

### PR DESCRIPTION
**Pull request by erenfro**
Proprietary office suite; word processing, spreadsheets, presentations; subscription edition

### CODE REVIEW

**Comment by erenfro** [comment]
Currently working on replaces/conflicts between softmaker-office-2024, softmaker-office-nx and softmaker-freeoffice-2024

**Comment by erenfro** [comment]
This is now ready for review.

**Comment by Elsie19** [comment]
This fails on a lot of things. Explicitly disable them with `incompatible` or figure out the issues some other way.

**Comment by Xdavius** [comment]
> This is now ready for review.

Please, fix PR title by adding -deb

**Review by oklopfer — APPROVED** [review]

**Pull request merged**
