### PR TITLE
upd(hypnotix-deb): `4.3` -> `4.8`

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Comment by Zahrun** [comment]
Requires https://github.com/pacstall/pacstall-programs/pull/6561

**Comment by vigress8** [comment]
`python3-imdbpy` has been [removed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1079959) from the Debian repositories

**Comment by Elsie19** [comment]
Has there been any new updates @Zahrun?

**Comment by Zahrun** [comment]
@Elsie19 Sorry I have been pretty busy and didn’t look into this
https://github.com/pacstall/pacstall-programs/pull/6756 should help

**Review by Elsie19 — APPROVED** [review]

**Pull request merged**
