### PR TITLE
fix(rhino*core): `2023.4-1` -> `2023.4-2`

### PR DESCRIPTION
**Pull request by ajstrongdev**
- bump: rhino-*-core pkgrel since Ubuntu updated /etc/os-release.

### CODE REVIEW

**Comment by oklopfer** [comment]
Fix title

**Comment by ajstrongdev** [comment]
> Fix title

To what?

PS: I did test it with pacstall-qa, and it works fine.

**Comment by oklopfer** [comment]
fix(rhino*core): `2023.4-1` -> `2023.4-2` or 

upd(rhino*core): `2023.4-1` -> `2023.4-2`

**Comment by ajstrongdev** [comment]
> fix(rhino*core): `2023.4-1` -> `2023.4-2` or
> 
> upd(rhino*core): `2023.4-1` -> `2023.4-2`

There.

**Pull request merged**
