### PR TITLE
add: `btrfs-du-bin`

### PR DESCRIPTION
**Pull request by Henryws**

### CODE REVIEW

**Comment by Henryws** [comment]
@brainchild0 mind testing?

If you are running `3.0.0` or higher
```bash
wget -q https://raw.githubusercontent.com/Henryws/pacstall-programs/add-btrfs-du/packages/btrfs-du-bin/btrfs-du-bin.pacscript
pacstall -I btrfs-du-bin.pacscript
```

If you are running `2.0.1` or lower
```bash
wget -q https://raw.githubusercontent.com/Henryws/pacstall-programs/add-btrfs-du/packages/btrfs-du-bin/btrfs-du-bin.pacscript
pacstall -Il btrfs-du-bin
```

**Comment by brainchild0** [comment]
```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
$ type btrfs-du
bash: type: btrfs-du: not found
$ pacstall -V
3.0.2 Picotee
$ wget -q https://raw.githubusercontent.com/Henryws/pacstall-programs/add-btrfs-du/packages/btrfs-du-bin/btrfs-du-bin.pacscript
$ pacstall -I btrfs-du-bin.pacscript
Do you want to view/edit the pacscript [y/N]
[+] INFO: Sourcing pacscript
[sudo] password:        
[*] WARNING: Package does not contain a hash
[*] WARNING: Package does not have a maintainer. Please be advised
[+] INFO: Retrieving packages
Initializing download: https://github.com/nachoparker/btrfs-du/archive/refs/tags/v0.0.7.tar.gz
File size: unavailable
Opening output file v0.0.7.tar.gz
Server unsupported, starting from scratch with one connection.
Starting download

Connection 0 finished

Downloaded 14.3447 Kilobyte(s) in 0 second(s). (71.40 KB/s)
[+] INFO: Extracting v0.0.7.tar.gz
[+] INFO: Running functions
	[>] Running install
install: creating directory '/usr/src/pacstall/btrfs-du-bin/usr'
install: creating directory '/usr/src/pacstall/btrfs-du-bin/usr/bin'
'btrfs-du' -> '/usr/src/pacstall/btrfs-du-bin/usr/bin/btrfs-du'
[+] INFO: Packaging btrfs-du-bin as btrfs-du
	[>] Packing control.tar
	[>] Packing data.tar
	[>] Compressing
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'btrfs-du' instead of '/usr/src/pacstall/btrfs-du-bin.deb'
The following NEW packages will be installed:
  btrfs-du
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/3054 B of archives.
After this operation, 5120 B of additional disk space will be used.
Get:1 /usr/src/pacstall/btrfs-du-bin.deb btrfs-du all 0.0.7 [3054 B]
Selecting previously unselected package btrfs-du.
(Reading database ... 1080609 files and directories currently installed.)
Preparing to unpack .../src/pacstall/btrfs-du-bin.deb ...
Unpacking btrfs-du (0.0.7) ...
Setting up btrfs-du (0.0.7) ...
[+] INFO: Performing post install operations
	[>] Storing pacscript
	[>] Cleaning up
$ type btrfs-du
btrfs-du is /usr/bin/btrfs-du
```

**Comment by brainchild0** [comment]
May I ask, why is the package name given as ending in `-bin`, following the project name?

**Comment by Henryws** [comment]
Because it downloads from a tag, and installs a single binary

Sent from Proton Mail mobile

-------- Mensaje original --------

**Comment by brainchild0** [comment]
What tag? Do you mean the Git tag?

**Review by wizard-28 — CHANGES_REQUESTED** [review]
`maintainer` missing

**Comment by wizard-28** [comment]
> What tag? Do you mean the Git tag?

Because it installs a binary directly, there's no compilation involved.

**Comment by brainchild0** [comment]
I see, but for the package name to  expose the distinction might reduce the level of user friendliness.

**Comment by Henryws** [comment]
> `maintainer` missing

I don't wish to maintain it.

**Pull request merged**
