### PR TITLE
upd(insync-deb): `3.8.1.50459` -> `3.8.4.50481`

### PR DESCRIPTION
**Pull request by wizard-28**

### CODE REVIEW

**Comment by wizard-28** [comment]
@Henryws any ideas?

**Comment by Henryws** [comment]
Add `incompatible`

**Comment by wizard-28** [comment]
> Add `incompatible`

Why? I've specifically included the debian deb.

**Comment by Henryws** [comment]
But it fails on Debian.

**Comment by wizard-28** [comment]
> But it fails on Debian.

That's what I'm asking you, do you have any ideas why it's failing? The CI isn't helpful.

**Comment by Henryws** [comment]
I got no idea.

**Comment by Henryws** [comment]
Oh it's sysctl. I'll merge it, most normal systems have it.

**Pull request merged**
