### PR TITLE
[Update] Fix `bpytop-git` dependency issues

### LINKED ISSUE #10: [bug] `bpytop-git` doesn't work
**Describe the bug**
`bpytop-git` doesn't work

**To Reproduce**
1. Install `bpytop-git` from pacstall
2. Run `bpytop`
3. See that it doesn't work.

**Expected behavior**
bpytop works

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04
 - Version: 1.3 Amaranth (develop)

**Additional context**
Here is the install logs
```
❯ sudo pacstall -I bpytop-git
bpytop-git.pacsc 100%[========>]     452  --.-KB/s    in 0s
Do you want to view the pacscript first [y/N]
Do you want to edit the pacscript [y/N] y
[+] INFO: Sourcing pacscript
[+] INFO: Running checks
[+] INFO: URL exists
[+] INFO: Installing dependencies
(Reading database ... 257680 files and directories currently installed.)
Preparing to unpack .../python3-lib2to3_3.8.10-0ubuntu1~20.04_all.deb ...
Unpacking python3-lib2to3 (3.8.10-0ubuntu1~20.04) over (3.8.2-1ubuntu1) ...
Preparing to unpack .../python3-distutils_3.8.10-0ubuntu1~20.04_all.deb ...
Unpacking python3-distutils (3.8.10-0ubuntu1~20.04) over (3.8.2-1ubuntu1) ...
Setting up python3-lib2to3 (3.8.10-0ubuntu1~20.04) ...
find: '/usr/lib/python3.7/lib2to3': No such file or directory
find: '/usr/lib/python3.7/lib2to3': No such file or directory
find: '/usr/lib/python3.7': No such file or directory
Setting up python3-distutils (3.8.10-0ubuntu1~20.04) ...
find: '/usr/lib/python3.7/distutils': No such file or directory
find: '/usr/lib/python3.7/distutils': No such file or directory
find: '/usr/lib/python3.7': No such file or directory
[+] INFO: Retrieving packages
Checking object directories: 100% (256/256), done.
[+] INFO: Installing
[+] INFO: Symlinking files
[+] INFO: Storing pacscript
```

Running `bpytop`
```
❯ bpytop
ERROR!
No module named 'psutil'

Install required modules!
```

Maintainer: [@WRM-42]

### PR DESCRIPTION
**Pull request by wizard-28**
This fixes #10

### CODE REVIEW

**Comment by wizard-28** [comment]
@WRM-42 might want to review this.

**Review by Henryws — COMMENTED** [review]
Looks good to me but we probs need wrm to give the ok

**Comment by wizard-28** [comment]
By the way, can we invite the maintainers to the pacstall organization, so we can add them as reviewers etc?

**Comment by wizard-28** [comment]
@Henryws Maybe add them as members of the organization?

**Comment by WRM-42** [comment]
You forgot to add python3-pip as a dependency.

**Review by WRM-42 — APPROVED** [review]
It should be good now.

**Pull request merged**
