### PR TITLE
PacReq: `walc-app`

### LINKED ISSUE #45: PacReq: WALC
An unofficial WhatsApp Desktop client for linux systems.

Url: https://github.com/cstayyab/WALC
Building Guide: https://github.com/cstayyab/WALC#manual-compilation-and-usage

Requested by: @AnonymouslyKnown 💘 on discord server

### PR DESCRIPTION
**Pull request by wizard-28**
This closes #45

### CODE REVIEW

**Review by Henryws — COMMENTED** [review]
```bash
Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/pacstall/WALC/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/pacstall/WALC/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! walc@0.2.1 build: `electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the walc@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/henry/.npm/_logs/2021-06-17T19_28_39_750Z-debug.log
[+] INFO: Installing
walc-git.pacscript: line 44: cd: dist/: No such file or directory
sudo: mmv: command not found
[+] INFO: Symlinking files
[+] INFO: Storing pacscript
➜  ~ pacstall -T walc-git
/
└── usr
    ├── bin
    └── share
        ├── doc
        │   └── walc
        │       └── README.md
        └── licenses
            └── walc
                └── LICENSE

7 directories, 2 files
➜  ~
```
It failed to build

**Comment by wizard-28** [comment]
I think its a problem with `pacstall -Il`, trying switching repos and install using `-I`

**Comment by Henryws** [comment]
> I think its a problem with `pacstall -Il`, trying switching repos and install using `-I`

Doesn't work

**Comment by wizard-28** [comment]
Well, can you send the full log from start to end?

**Comment by Henryws** [comment]
```bash
➜  ~ pacstall -I walc-git
walc-git.pacscript      100%[============================>]   1.42K  --.-KB/s    in 0.001s
Do you want to view the pacscript first [y/N] y
Do you want to edit the pacscript [y/N] n
[+] INFO: Sourcing pacscript
[+] INFO: URL exists
[*] WARNING: Package does not contain a hash
[+] INFO: Installing dependencies
[+] INFO: Retrieving packages
Checking object directories: 100% (256/256), done.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> deasync@0.1.21 install /tmp/pacstall/WALC/node_modules/deasync
> node ./build.js

`linux-x64-node-10` exists; testing
Binary is fine; exiting

> core-js@3.14.0 postinstall /tmp/pacstall/WALC/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@11.4.8 postinstall /tmp/pacstall/WALC/node_modules/electron
> node install.js


> walc@0.2.1 postinstall /tmp/pacstall/WALC
> electron-builder install-app-deps

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/pacstall/WALC/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/pacstall/WALC/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! walc@0.2.1 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the walc@0.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/henry/.npm/_logs/2021-06-17T19_31_48_852Z-debug.log

> walc@0.2.1 build /tmp/pacstall/WALC
> electron-builder

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/pacstall/WALC/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/pacstall/WALC/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! walc@0.2.1 build: `electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the walc@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/henry/.npm/_logs/2021-06-17T19_31_50_438Z-debug.log
[+] INFO: Installing
walc-git.pacscript: line 44: cd: dist/: No such file or directory
sudo: mmv: command not found
[+] INFO: Symlinking files
[+] INFO: Storing pacscript
➜  ~
```

**Comment by Henryws** [comment]
Is this ready to merge?

**Comment by wizard-28** [comment]
@Henryws What is your node version?

**Comment by Henryws** [comment]
> @Henryws What is your node version?

v12.22.0

**Comment by wizard-28** [comment]
> v12.22.0

Upgrade to node >= 14

**Comment by Henryws** [comment]
It's v16.5.0 now

**Comment by wizard-28** [comment]
> It's v16.5.0 now

Try to install this package again

**Comment by Henryws** [comment]
Oh, I thought you mean't on my main computer. hold on

**Comment by Henryws** [comment]
```bash
[+] INFO: Retrieving packages
logname: no login name
logname: no login name
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> deasync@0.1.21 install /tmp/pacstall/WALC/node_modules/deasync
> node ./build.js

`linux-x64-node-10` exists; testing
Binary is fine; exiting

> core-js@3.15.2 postinstall /tmp/pacstall/WALC/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@11.4.10 postinstall /tmp/pacstall/WALC/node_modules/electron
> node install.js

npm WARN lifecycle walc@0.2.1~postinstall: cannot run in wd walc@0.2.1 electron-builder install-app-deps (wd=/tmp/pacstall/WALC)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for builder-util-runtime@8.7.5: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: builder-util-runtime@8.7.5
npm WARN notsup Unsupported engine for fs-extra@10.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fs-extra@10.0.0
npm WARN notsup Unsupported engine for electron-builder@22.11.7: wanted: {"node":">=14.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: electron-builder@22.11.7
npm WARN notsup Unsupported engine for laravel-mix@6.0.25: wanted: {"node":">=12.14.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: laravel-mix@6.0.25
npm WARN notsup Unsupported engine for app-builder-lib@22.11.7: wanted: {"node":">=14.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: app-builder-lib@22.11.7
npm WARN notsup Unsupported engine for builder-util-runtime@8.7.7: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: builder-util-runtime@8.7.7
npm WARN notsup Unsupported engine for read-config-file@6.2.0: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: read-config-file@6.2.0
npm WARN notsup Unsupported engine for yargs@17.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: yargs@17.0.1
npm WARN notsup Unsupported engine for builder-util-runtime@8.7.7: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: builder-util-runtime@8.7.7
npm WARN notsup Unsupported engine for builder-util-runtime@8.7.7: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: builder-util-runtime@8.7.7
npm WARN notsup Unsupported engine for builder-util-runtime@8.7.7: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: builder-util-runtime@8.7.7
npm WARN notsup Unsupported engine for builder-util-runtime@8.7.6: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: builder-util-runtime@8.7.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dmg-license@^1.0.9 (node_modules/dmg-builder/node_modules/dmg-license):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for dmg-license@1.0.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for img-loader@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: img-loader@4.0.0
npm WARN notsup Unsupported engine for postcss-loader@6.1.1: wanted: {"node":">= 12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: postcss-loader@6.1.1
npm WARN notsup Unsupported engine for webpack-dev-server@4.0.0-beta.3: wanted: {"node":">= 12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: webpack-dev-server@4.0.0-beta.3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for webpack-dev-middleware@4.3.0: wanted: {"node":">= v10.23.3"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: webpack-dev-middleware@4.3.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iconv-corefoundation@^1.1.6 (node_modules/dmg-license/node_modules/iconv-corefoundation):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for iconv-corefoundation@1.1.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1265 packages from 737 contributors and audited 1270 packages in 35.87s

111 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> walc@0.2.1 build /tmp/pacstall/WALC
> electron-builder

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/pacstall/WALC/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/pacstall/WALC/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! walc@0.2.1 build: `electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the walc@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-16T15_52_05_878Z-debug.log
[+] INFO: Installing
walc-git.pacscript: line 44: cd: dist/: No such file or directory
WALC-*.AppImage -> /usr/src/pacstall/walc-git/usr/bin/walc : no match.
Nothing done.
[+] INFO: Symlinking files
[+] INFO: Storing pacscript
```

**Comment by wizard-28** [comment]
> {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})

Your node is outdated?...

**Comment by Henryws** [comment]
Then how should ubuntu install the proper nodejs? It's already trying to install the latest

**Comment by wizard-28** [comment]
What is your output of `node -v`

**Comment by Henryws** [comment]
`v10.19.0`

**Comment by wizard-28** [comment]
Execute this: `curl -sL install-node.now.sh/lts | sudo bash`

**Comment by Henryws** [comment]
```bash
root@be9d1137a124:/# node -v
v10.19.0
root@be9d1137a124:/# curl -sL install-node.now.sh/lts | sudo bash
  Configuration
> Version:  v14.17.3 (resolved from lts)
> Prefix:   /usr/local
> Platform: linux
> Arch:     x64

> Tarball URL: https://nodejs.org/dist/v14.17.3/node-v14.17.3-linux-x64.tar.gz
? Install Node.js v14.17.3 to /usr/local? [yN] y
> Installing Node.js, please wait…
✓ Done
root@be9d1137a124:/# node -v
v10.19.0
root@be9d1137a124:/#
```

**Comment by wizard-28** [comment]
Execute `/usr/local/bin/node -v`

**Comment by Henryws** [comment]
`v14.17.3`

**Comment by wizard-28** [comment]
> `v14.17.3`

That means you have currently two versions of node installed in your system, one by `APT` and one by the `curl` command.

Uninstall the one installed by `APT` to make the system default to the `curl` installation.

Then rerun the package installation

**Comment by Henryws** [comment]
Testing now, but noticed when you don't run `hash -r` (clean PATH database) after removing node from apt, it returns an error, but when you run it, it prints the correct version

**Comment by Henryws** [comment]
```bash
[+] INFO: Retrieving packages
logname: no login name
logname: no login name
Checking object directories: 100% (256/256), done.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> deasync@0.1.21 install /tmp/pacstall/WALC/node_modules/deasync
> node ./build.js

`linux-x64-node-14` exists; testing
Binary is fine; exiting

> core-js@3.15.2 postinstall /tmp/pacstall/WALC/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@11.4.10 postinstall /tmp/pacstall/WALC/node_modules/electron
> node install.js

npm WARN lifecycle walc@0.2.1~postinstall: cannot run in wd walc@0.2.1 electron-builder install-app-deps (wd=/tmp/pacstall/WALC)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dmg-license@^1.0.9 (node_modules/dmg-builder/node_modules/dmg-license):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for dmg-license@1.0.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iconv-corefoundation@^1.1.6 (node_modules/dmg-license/node_modules/iconv-corefoundation):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for iconv-corefoundation@1.1.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1265 packages from 737 contributors and audited 1270 packages in 21.1s

111 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> walc@0.2.1 build /tmp/pacstall/WALC
> electron-builder

  • electron-builder  version=22.11.7 os=5.10.49-1-lts
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=11.4.10 appOutDir=dist/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v11.4.10/electron-v11.4.10-linux-x64.zip size=76 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v11.4.10/electron-v11.4.10-linux-x64.zip duration=4.442s
  • building        target=AppImage arch=x64 file=dist/WALC-0.2.1.AppImage
  • building        target=snap arch=x64 file=dist/walc_0.2.1_amd64.snap
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z size=1.5 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=595ms
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z duration=643ms
[+] INFO: Installing
[+] INFO: Symlinking files
[+] INFO: Storing pacscript
root@be9d1137a124:/# echo $?
0
root@be9d1137a124:/#
```
It says it worked, but running `walc` say's no such file or directory, and a binary called `walc` is in `/usr/bin`, but running it says no such file or directory

**Comment by wizard-28** [comment]
`It says it worked, but running walc say's no such file or directory, and a binary called walc is in /usr/bin, but running it says no such file or directory`

What happens when you run `/usr/bin/walc`?

**Comment by Henryws** [comment]
> > `It says it worked, but running walc say's no such file or directory, and a binary called walc is in /usr/bin, but running it says no such file or directory`
> 
> What happens when you run `/usr/bin/walc`?

That's what I'm saying. It say's 
```bash
root@be9d1137a124:/# /usr/bin/walc
bash: /usr/bin/walc: No such file or directory
```

**Comment by wizard-28** [comment]
> `/usr/bin/walc`

Wait, so is the file (binary) actually present in `/usr/bin/`?

Also run `sudo find / -name walc`

**Comment by Henryws** [comment]
> > `/usr/bin/walc`
> 
> Wait, so is the file (binary) actually present in `/usr/bin/`?
> 
> Also run `sudo find / -name walc`

Yes, the file is present and opening it in a text editor looks to be a binary

**Comment by wizard-28** [comment]
Can you `sudo chmod +x.....` it?

**Comment by Henryws** [comment]
> Can you `sudo chmod +x.....` it?

Doesn't work

**Comment by wizard-28** [comment]
It's acutally an AppImage? So, do they work correctly on your system?

**Comment by Henryws** [comment]
> It's acutally an AppImage? So, do they work correctly on your system?

oh, maybe

> It's acutally an AppImage. So, do they work correctly on your system?

How do you install appimage again?

**Comment by wizard-28** [comment]
@AnonymouslyKnown didn't have to do anything on their system. It just worked in their machine...

**Comment by Henryws** [comment]
> @AnonymouslyKnown didn't have to do anything on their system. It just worked in their machine...

Could it be that I'm running it in a docker container?

**Comment by wizard-28** [comment]
> Could it be that I'm running it in a docker container?

I have exactly 0 experience with docker, can' tell.

**Comment by Henryws** [comment]
> > Could it be that I'm running it in a docker container?
> 
> I have exactly 0 experience with docker, can' tell.

```bash
endmc@endmc:~$ walc
Checking for update
Segmentation fault (core dumped)
endmc@endmc:~$
```

**Comment by wizard-28** [comment]
> Segmentation fault (core dumped)

Amazing. I faced this problem earlier with `fastfetch`... Looks like we need to make an issue on their (`walc`'s) github.

**Comment by Henryws** [comment]
> > Segmentation fault (core dumped)
> 
> Amazing. I faced this problem earlier with `fastfetch`... Looks like we need to make an issue on their (`walc`'s) github.

Did it work on anonymous' machine?

**Comment by wizard-28** [comment]
> Did it work on anonymous' machine?

According to him yes. Should we contact him on discord?

**Review by D-Brox — APPROVED** [review]

**Pull request merged**
