### PR TITLE
upd(obsidian-deb): `1.3.7` -> `1.4.16`

### PR DESCRIPTION
**Pull request by Craftidore**
Obsidian 1.4.16 fixes a major Electron security issue, and as such it's necessary to update from 1.3.7.

### CODE REVIEW

**Comment by thomascrha** [comment]
Can confirm this works if i download the file and manually install with `pacstall -I obsidian-deb.pacscript` - You beat me to it - was just about to push a PR for this update - Thank You @Craftidore

**Comment by Elsie19** [comment]
Fix the title in accordance to [other update PRs](https://github.com/pacstall/pacstall-programs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3A%22Update+Package%22).

**Comment by Elsie19** [comment]
> Can confirm this works if i download the file and manually install with `pacstall -I obsidian-deb.pacscript` - You beat me to it - was just about to push a PR for this update - Thank You @Craftidore

You can also do:

```bash
$ pacstall -I pacstall-qa-git
$ pacstall-qa -m github:pacstall/pacstall-programs/4672 -I obsidian-deb
```
now!

**Review by Elsie19 — APPROVED** [review]

**Comment by thomascrha** [comment]
That simplifies things !! @Elsie19

**Pull request merged**
