### PR TITLE
upd(makedeb-deb): 9.0.3-1 -> 10.0.0

### PR DESCRIPTION
**Pull request by warofzen**

### CODE REVIEW

**Review by Henryws — APPROVED** [review]

**Review by wizard-28 — CHANGES_REQUESTED** [review]
So, who's the maintainer?

**Comment by Henryws** [comment]
I believe I made the script and hunter didn't want to maintain it

**Comment by wizard-28** [comment]
> I believe I made the script and hunter didn't want to maintain it

So, as per tradition you're the maintainer now.

**Comment by wizard-28** [comment]
So @Henryws add yourself as the maintainer.

**Pull request merged**
