### PR TITLE
add: `nerd-fonts-hack`

### PR DESCRIPTION
**Pull request by Henryws**

### CODE REVIEW

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Run the pre-commit hooks for your pacscript

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Add these missing fields

1. `repology`
2. `breaks`
3. `gives`

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Install the `LICENSE`

**Comment by Henryws** [comment]
> Install the `LICENSE`

The zip file doesn't contain a license file.

**Pull request merged**
