### PR TITLE
upd(heroic-games-launcher-deb): `2.11.0` -> `2.12.0`

### PR DESCRIPTION
**Pull request by Panda-Code-Master**
Updating from v2.11.0 to v2.12.0

### CODE REVIEW

**Comment by Elsie19** [comment]
Fix the title and merge from master.

**Comment by Panda-Code-Master** [comment]
> Fix the title and merge from master.

i don't know what you mean this is my first pull and merge request

**Comment by vigress8** [comment]
@Panda-Code-Master this is the format:
```
upd($name): `$pkgver_old` -> `$pkgver_new`
```
In this case:
```
upd(heroic-games-launcher-deb): `2.11.0` -> `2.12.0`
```

**Comment by Panda-Code-Master** [comment]
> @Panda-Code-Master this is the format:
> 
> ```
> upd($name): `$pkgver_old` -> `$pkgver_new`
> ```
> 
> In this case:
> 
> ```
> upd(heroic-games-launcher-deb): `2.11.0` -> `2.12.0`
> ```

Thanks a lot

**Review by Elsie19 — APPROVED** [review]

**Pull request merged**
