### PR TITLE
[Package Add] rust-analyzer

### PR DESCRIPTION
**Pull request by JonBoyleCoding**

### CODE REVIEW

**Review by wizard-28 — COMMENTED** [review]
Can you send the compilation log, when running this? The CI is failing.

**Comment by Henryws** [comment]
I think the problem is that he's using _version in the pacscript

**Comment by JonBoyleCoding** [comment]
Weird... it's working fine on my machine. Time to Debug! 

The _version idea came from the AUR version of the package - although I'm not sure it's actually working here.

jonathan@computer:~/$ echo $_version
2021-06-28
jonathan@computer:~/$ echo ${_version//-}
20210628
xlk
Looking at the CI, the build stage fails due to a permissions issue during the:

> error: Permission denied (os error 13) at path "/tmp/pacstall/rust-analyzer-2021-06-28/target0RoVdj"

**Comment by JonBoyleCoding** [comment]
Weird... it's working fine on my machine. Time to Debug! 

The _version idea came from the AUR version of the package - although I'm not sure it's actually working with pacstall as it seems to still use the -s in the folder structure when building. What it should do is remove the -s like the following:

```
jonathan@computer:~/$ echo $_version
2021-06-28
jonathan@computer:~/$ echo ${_version//-}
20210628
```

Looking at the CI, the build stage fails due to a permissions issue during the build with cargo:

> error: Permission denied (os error 13) at path "/tmp/pacstall/rust-analyzer-2021-06-28/target0RoVdj"

I can't figure out where this is coming from. On my machine, it downloads the rust packages and compiles them fine. However, I do have cargo installed locally in my user account rather than Ubuntu's version. I'll see what happens on a different user account.

**Comment by JonBoyleCoding** [comment]
Well I get a completely different error under a different user:

```
Do you want to view the pacscript first [y/N]
Do you want to edit the pacscript [y/N]
[+] INFO: Sourcing pacscript
[+] INFO: URL exists
[+] INFO: rust-analyzer requires cargo to install
Do you want to remove them after installing rust-analyzer [y/N] y
[+] INFO: Installing dependencies
[+] INFO: Retrieving packages
2021-06-28.tar.gz             100%[================================================>]   1.81M  --.-KB/s    in 0.1s
error: failed to parse manifest at `/tmp/pacstall/rust-analyzer-2021-06-28/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
[+] INFO: Installing
install: cannot stat 'target/release/rust-analyzer': No such file or directory
[+] INFO: Symlinking files
[+] INFO: Storing pacscript
```
I'm guessing this means that the Ubuntu version of cargo doesn't have a feature required to build the program. Makes me wonder then how cargo on the CI gets further though... does it install it's own version of cargo at some point?

**Comment by Henryws** [comment]
The CI runs on Ubuntu LTS

**Comment by Henryws** [comment]
Looking at the ci, it didn't work either even though it says it did

**Comment by JonBoyleCoding** [comment]
I think I will put this on hold until rust version is sorted out - I'll do some tests offline.

**Pull request closed without merging**
