### PR TITLE
add: `oh-my-posh-git`

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Review by Elsie19 — CHANGES_REQUESTED** [review]
CI fails.

**Comment by Zahrun** [comment]
> CI fails.

For some reason, pacstall fails to install nerd-fonts-hack as a pacdep. If I install the pacdep manually with `pacstall -I nerd-fonts-hack`, then it works.

**Comment by Zahrun** [comment]
The CI removes nerd-fonts-hack, which automatically removes oh-my-posh-git, and then tries to remove oh-my-posh-git, but fails because it already automatically was removed

**Comment by oklopfer** [comment]
@Zahrun other than the CI's uninstall error, is your package all good to go?

**Comment by Zahrun** [comment]
> @Zahrun other than the CI's uninstall error, is your package all good to go?

Yes

**Pull request merged**
