### PR TITLE
fix(fsearch-deb): new urls and hashes

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Comment by Zahrun** [comment]
debian:stable CI fails but I can’t reproduce

**Comment by Henryws** [comment]
Fix the title.

**Comment by Zahrun** [comment]
> Fix the title.

Version is still 0.2.2 though

**Comment by Henryws** [comment]
Then why did you use the `upd` prefix?

**Comment by Zahrun** [comment]
I guess it’s a fix then

**Pull request merged**
