### PR TITLE
upd(kvantum): `1.0.0` -> `1.0.1`

### PR DESCRIPTION
**Pull request by Henryws**

### CODE REVIEW

**Comment by Henryws** [comment]
image
CI fails but works in a completely clean Ubuntu LTS docker container.

**Comment by wizard-28** [comment]
> image
> CI fails but works in a completely clean Ubuntu LTS docker container.

It fails on Debian stable 

```
Could not find a configuration file for package "KF5WindowSystem" that is 
compatible with requested version "5.82.0". 

The following configuration files were considered but not accepted: 

/usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake, version: 5.78.0
```


The dependency version is outdated on Debian stable

**Comment by wizard-28** [comment]
So, what to do @Henryws?

**Comment by Henryws** [comment]
> So, what to do @Henryws?

Block on Debian I guess.

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
