### PR TITLE
upd(minecraft-pi-reborn-app): `2.3.13` -> `2.4.2`

### PR DESCRIPTION
**Pull request by cat-master21**

### CODE REVIEW

**Comment by Henryws** [comment]
CI fails

**Comment by Henryws** [comment]
Still fails. Can you try installing this locally?

**Comment by cat-master21** [comment]
when running podman in the official container I get:
```
pacstall@50080408e512:~$ pacstall --disable-prompts -Il minecraft-pi-reborn-app.pacscript 
[*] WARNING: Prompts are disabled
Do you want to view/edit the pacscript [y/N] N
[+] INFO: Sourcing pacscript
[+] INFO: Creating dummy package
[+] INFO: Installing dependencies
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'minecraft-pi-reborn-app' instead of '/tmp/pacstall/minecraft-pi-reborn-app-pacstall.deb'
minecraft-pi-reborn-app is already the newest version (2.4.2-1).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
[+] INFO: Retrieving packages
Initializing download: https://jenkins.thebrokenrail.com/job/minecraft-pi-reborn/job/master/237/artifact/out/minecraft-pi-reborn-client-2.4.2-amd64.AppImage
File size: 7.27069 Megabyte(s) (7623872 bytes)
Opening output file minecraft-pi-reborn-client-2.4.2-amd64.AppImage
Error opening local file
[!] ERROR: Failed to download package
[+] INFO: Cleaning up
```
?

**Comment by cat-master21** [comment]
And yes network does work on it too as I downloaded the pacscript inside the container.

**Comment by cat-master21** [comment]
Yeah I can download the file both by cURL and Wget:
```
pacstall@50080408e512:~$ curl https://jenkins.thebrokenrail.com/job/minecraft-pi-reborn/job/master/237/artifact/out/minecraft-pi-reborn-client-2.4.2-amd64.AppImage -o ./pi.AppImage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
pacstall@50080408e512:~$ ls ./
log.txt  minecraft-pi-reborn-app.pacscript  pi.AppImage
pacstall@50080408e512:~$
```

**Comment by Henryws** [comment]
Hmm, run `source minecraft-pi-reborn-app.pacscript && wget $url`

**Comment by Henryws** [comment]
image
hmm.

**Comment by Henryws** [comment]
I found the issue:

image

The last url (https://gitea.thebrokenrail.com/TheBrokenRail/minecraft-pi-reborn/raw/tag/2.4.2/launcher/data/client/share/applications/com.thebrokenrail.MCPIRebornClient.desktop) doesn't exit

**Review by Henryws — APPROVED** [review]

**Pull request merged**
