### PR TITLE
upd(spotify-client-deb): `1.1.84.716.gc5f8b819` -> `1.1.84.716.gc5f8b819-2`

### PR DESCRIPTION
**Pull request by AloneER0**
Updated spotify-client-deb from ``1.1.84.716.gc5f8b819`` to ``1.1.84.716.gc5f8b819-2``

Everything should be working fine

### CODE REVIEW

**Comment by Henryws** [comment]
Fix the PR title.

**Comment by AloneER0** [comment]
To what?

**Comment by Henryws** [comment]
Like #2640.

**Comment by AloneER0** [comment]
Ah I see

**Comment by AloneER0** [comment]
Better?

**Comment by Henryws** [comment]
Add the backticks

**Comment by AloneER0** [comment]
Done!

**Comment by Henryws** [comment]
Single backticks

**Comment by AloneER0** [comment]
Now good? 🤔

**Review by Henryws — APPROVED** [review]

**Pull request merged**
