### PR TITLE
fix(github-desktop-deb): repology version fix

### PR DESCRIPTION
**Pull request by Henryws**

### CODE REVIEW

**Review by cat-master21 — CHANGES_REQUESTED** [review]
Have it where there is a separate variable for the full version like the PKGBUILD in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=github-desktop

**Comment by Henryws** [comment]
I don't think we need a separate variable for the `-linux2`

**Comment by cat-master21** [comment]
Well we definitely don't need one but it may be better to have a variable. I'm fine if don't though.

**Comment by Henryws** [comment]
Well, it seems that they change the suffix every other release, so it might be useful to add a variable. For now, I think not adding one is fine.

**Review by cat-master21 — APPROVED** [review]

**Pull request merged**
