### PR TITLE
upd(discord-canary): `0.0.132` -> `0.0.133`

### PR DESCRIPTION
**Pull request by warofzen**

### CODE REVIEW

**Review by wizard-28 — APPROVED** [review]

**Review by wizard-28 — CHANGES_REQUESTED** [review]
> ```yaml
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> The following packages have unmet dependencies:
>  discord-canary : Depends: libappindicator1 but it is not installable
> ```

Doesn't work for debian @Henryws

**Comment by Mar0xy** [comment]
> > ```yaml
> > Some packages could not be installed. This may mean that you have
> > requested an impossible situation or if you are using the unstable
> > distribution that some required packages have not yet been created
> > or been moved out of Incoming.
> > The following information may help to resolve the situation:
> > The following packages have unmet dependencies:
> >  discord-canary : Depends: libappindicator1 but it is not installable
> > ```
> 
> Doesn't work for debian @Henryws

https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages
"The deprecated libappindicator libraries are no longer provided. As a result, the related packages libappindicator1, libappindicator3-1 and libappindicator-dev are no longer available. This is expected to cause dependency errors for third-party software that still depends on libappindicator to provide system tray and indicator support.

Debian is using libayatana-appindicator as the successor of libappindicator."

**Comment by wizard-28** [comment]
> > > ```yaml
> > > Some packages could not be installed. This may mean that you have
> > > requested an impossible situation or if you are using the unstable
> > > distribution that some required packages have not yet been created
> > > or been moved out of Incoming.
> > > The following information may help to resolve the situation:
> > > The following packages have unmet dependencies:
> > >  discord-canary : Depends: libappindicator1 but it is not installable
> > > ```
> > 
> > 
> > Doesn't work for debian @Henryws
> 
> https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages "The deprecated libappindicator libraries are no longer provided. As a result, the related packages libappindicator1, libappindicator3-1 and libappindicator-dev are no longer available. This is expected to cause dependency errors for third-party software that still depends on libappindicator to provide system tray and indicator support.
> 
> Debian is using libayatana-appindicator as the successor of libappindicator."

So, I guess we can't do nothing about this till discord updates it's dependencies? Or will just installing `libayatana-appindicator` instead of `libappindicator` work OOTB?

**Comment by Mar0xy** [comment]
> So, I guess we can't do nothing about this till discord updates it's dependencies? Or will just installing `libayatana-appindicator` instead of `libappindicator` work OOTB?

Since this is using a tar.gz and not installing from a deb it can simply be replaced by libayatana-appindicator

**Comment by Mar0xy** [comment]
> Is `libayatana-appindicator` available in Debian repos?

They are respectively called the same like libappindicator basically: libayatana-appindicator3-1 (GTK3) libayatana-appindicator1 (GTK2)

**Comment by Henryws** [comment]
So is there an appindicator that have a common name between Debian and Ubuntu?

**Comment by Henryws** [comment]
Then we should use that.

**Comment by Mar0xy** [comment]
So that means he would need to replace libappindicator1 with libayatana-appindicator1

**Comment by Henryws** [comment]
> So that means he would need to replace libappindicator1 with libayatana-appindicator1

@warofzen please do these changes

**Comment by wizard-28** [comment]
@aranym0 Do you wish to continue maintaining this package?

**Comment by wizard-28** [comment]
Merging for now as 1 day has passed, @aranym0 can contact later in this PR.

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
