### PR TITLE
upd(github-cli-deb): `2.11.3` ->`2.12.1`

### PR DESCRIPTION
**Pull request by theblobscp**

### CODE REVIEW

**Comment by Henryws** [comment]
Change PR title to conform to our standards

**Comment by theblobscp** [comment]
I also realized that i forgot to update the hash. Working on both now

**Comment by theblobscp** [comment]
@Henryws does this work?

**Comment by Henryws** [comment]
Check the CI ;)

**Review by Henryws — APPROVED** [review]

**Pull request merged**
