### PR TITLE
fix(discord-canary): prevent force update message

### PR DESCRIPTION
**Pull request by Elsie19**

### CODE REVIEW

**Comment by vigress8** [comment]
Does Discord create this file at launch? If so, this needs testing to make sure nothing breaks

**Comment by Elsie19** [comment]
I don't believe so but let me check.

**Comment by Elsie19** [comment]
Have confirmed it does not create on the first go.

**Review by vigress8 — APPROVED** [review]
LGTM, might as well add this for `discord` too

**Pull request merged**
