### PR TITLE
upd(librewolf-app): `125.0.3-1` -> `130.0-3` and upd(lunacy-deb): `9.5.0` -> `10.1`

### PR DESCRIPTION
**Pull request by jimed-rand**
Like `librewolf-deb` update the version from `125.0.3-1` -> `130.0-3`. Please review immediately when there's aren't found something wrong.

### CODE REVIEW

**Comment by vigress8** [comment]
Please don't update 2 unrelated packages in one PR.
I've also noticed you're working exclusively in the `master` branch - create a new branch for each PR instead

**Comment by jimed-rand** [comment]
Cause `librewolf-app` are still reviewing and now I update the `lunacy-deb`, so I change the title and add the updates for `lunacy-deb`. I'll waiting for evaluation if something's wrong or merge it when everything are okay.

**Comment by jimed-rand** [comment]
> Please don't update 2 unrelated packages in one PR. I've also noticed you're working exclusively in the `master` branch - create a new branch for each PR instead

Should I revert it ?

**Comment by vigress8** [comment]
Make sure to read [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches), it explains how to work with branches

**Comment by jimed-rand** [comment]
> Make sure to read [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches), it explains how to work with branches

Thanks for the references, I should be careful next time.

**Pull request closed without merging**
