### PR TITLE
fix: tmux pacscript 

### PR DESCRIPTION
**Pull request by harsh18262**
Fix for Issue #810

### CODE REVIEW

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Check the CI, the build fails.

**Comment by harsh18262** [comment]
That is the problem from ubuntu 20.04 as stow is not available in ubuntu 20.04 repositories we will need to add bionic repos and then install stow after that it will install success fully

**Comment by harsh18262** [comment]
I think there is a problem with pacstall it is not installing optional dependencies on ubuntu ,it is installing on debian .I also tried on ubuntu bionic docker image with the neofetch package for that package also pacstall is not installing optional dependencies

**Comment by wizard-28** [comment]
@Henryws can you reproduce this?

**Comment by Henryws** [comment]
> @Henryws can you reproduce this?

Yes (we should probably make apt install suggested packages), and also, the optdepends package should be in the depends variable, as it fails to build without it.

**Comment by wizard-28** [comment]
Linking: https://github.com/pacstall/pacstall/pull/519

**Review by Henryws — APPROVED** [review]

**Review by wizard-28 — CHANGES_REQUESTED** [review]
> `configure: error: "utempter not found"`

Check the CI logs, and add that dependency.

**Comment by harsh18262** [comment]
> > `configure: error: "utempter not found"`
> 
> Check the CI logs, and add that dependency.

It will be fixed as soon as PR [#528](https://github.com/pacstall/pacstall/pull/528) in pacstall repo is merged. The issue is that the optional dependencies is not being installed

**Pull request merged**
