### PR TITLE
add: `boosteroid-deb`

### PR DESCRIPTION
**Pull request by DismissedGuy**
Is the pacscript fine like this? Boosteroid only provides a generic download url, so it will cause a hash mismatch if they release an update...

### CODE REVIEW

**Comment by Henryws** [comment]
Is there anywhere that provides a versioned URL?

**Comment by DismissedGuy** [comment]
I spent some time hunting for it but couldn't find any. Even the version log the client downloads just seems to point to a generic `Bin.7z`. The [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=boosteroid) also points to the unversioned one, so I don't think any exist.

**Comment by Henryws** [comment]
Then I don't think that this package should become a pacscript if it can't provide a versioned URL.

**Comment by DismissedGuy** [comment]
How about using `pkgver` to essentially make it autoupdate? The wiki is a bit contradicting on whether to allow pkgver for non-git packages though.

**Comment by Henryws** [comment]
> The wiki is a bit contradicting on whether to allow pkgver for non-git packages though.

Don't use it for non-git packages.

**Comment by DismissedGuy** [comment]
Understood. In that case it would indeed be impossible to realize this as a proper pacscript.

**Pull request closed without merging**
