### PR TITLE
[Draft] Add cutefish

### PR DESCRIPTION
**Pull request by titenko**

### CODE REVIEW

**Comment by rain1598** [comment]
please keep it to one pacscript per PR

**Comment by rain1598** [comment]
please change the name to `[Package Add] package-name`

**Comment by Henryws** [comment]
> please keep it to one pacscript per PR

It's ok for this pr. I've talked to the guy on discord

**Comment by titenko** [comment]
Cutefish DE repository

**Comment by NarutoXY** [comment]
> please keep it to one pacscript per PR

Well since it is a DE add request, it is necessary to have multiple pacscripts as DE may depend on other stuff

**Comment by titenko** [comment]
Packages are dependent on each other. I checked on my local repository - everything works

**Comment by titenko** [comment]
> > please keep it to one pacscript per PR
> 
> Well since it is a DE add request, it is necessary to have multiple pacscripts as DE may depend on other stuff

Packages are dependent on each other. I checked on my local repository - everything works

**Comment by NarutoXY** [comment]
So is it ready to be merged?

**Comment by Henryws** [comment]
@titenko can you update the branch

**Pull request merged**
