### PR TITLE
add: `kalendar-git`

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Review by Henryws — CHANGES_REQUESTED** [review]
Check CI logs

**Comment by Zahrun** [comment]
> Check CI logs

Kalendar requires KFrameworks 5.88 and version 21.12 of the KDE PIM-related dependencies (e.g. Akonadi, kdepim-runtime) to be installed.
It will not build in debian stable. Only Ubuntu 22.04+

**Comment by Henryws** [comment]
@wizard-28 what to do

**Review by Henryws — APPROVED** [review]
welp, it works on ubuntu, so merging.

**Pull request merged**
