### PR TITLE
upd(the-honkers-railway-launcher-bin): `1.7.1` -> `1.8.1`

### PR DESCRIPTION
**Pull request by vbrabandt2005**

### CODE REVIEW

**Review by AozoraDev — APPROVED** [review]
LGTM

**Review by AozoraDev — CHANGES_REQUESTED** [review]
Maybe add git and webp as depends so *trailblazers* doesn't have to see this window.
image

**Review by AozoraDev — APPROVED** [review]
Yep. LGTM.

**Comment by vbrabandt2005** [comment]
> Yep. LGTM.

Thanks for the suggestion, I actually thought these dependencies were there in the pacscript or was preinstalled on ubuntu by default but I guess not, but yeah I added the same dependencies to all of the launchers associated.

**Review by Elsie19 — APPROVED** [review]

**Pull request merged**
