### PR TITLE
add: `ungoogled-chromium-deb`

### PR DESCRIPTION
**Pull request by jimed-rand**
This commit is based on request #1726.

### CODE REVIEW

**Comment by jimed-rand** [comment]
Before merge this commit, I suggest to merge first commit #6441 cause it's important dependences for `ungoogled-chromium-deb` or #6440

**Comment by jimed-rand** [comment]
Now it's back to review mode and now #6443 are replacing the #6441

**Comment by vigress8** [comment]
This Chromium version is years old and unsupported. Please use the latest available version

**Comment by jimed-rand** [comment]
> This Chromium version is years old and unsupported. Please use the latest available version

I know it's kinda old, but that's only one `deb` version available. But for `app` version, it has newest version.

**Comment by jimed-rand** [comment]
I should convert back into draft and find the newest version first.

**Comment by jimed-rand** [comment]
I got the newest version @vigress8 
Ready to review again.

**Comment by jimed-rand** [comment]
After tests, the package are not compatible and need more depends on `debian:stable` which it still uses Bookworm, but there's okay on another version. I'll add `debian:stable' as incompatible flag

**Pull request closed without merging**
