### PR TITLE
add: `fsearch-deb`

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Review by Henryws — CHANGES_REQUESTED** [review]
Add `libicu71-deb` as a pacdep

**Comment by Henryws** [comment]
CI fails.

**Comment by Zahrun** [comment]
> CI fails.

```
[!] ERROR: Failed to download the libicu71-deb pacscript
[⠿] Suggested solutions are:
    | Confirm that the package exists by running 'pacstall -S libicu71-deb'
    | Check your internet connection
[!] ERROR: The URL cannot be found
[⠿] Suggested solution is:
    | Confirm that 'https://raw.githubusercontent.com/pacstall/pacstall-programs/master/packages/libicu71-deb/libicu71-deb.pacscript/packagelist' exists
```

**Comment by Zahrun** [comment]
@Henryws I’ll fix the urls

**Review by Henryws — APPROVED** [review]

**Pull request merged**
