### PR TITLE
Use the `pkgver()` function in all scripts applicable

### LINKED ISSUE #12: [Feature] Use the new `pkgver()` function in `-git` pacscripts.
**Is your feature request related to a problem? Please describe.**
From Pacstal 1.3 "Amaranth" a new `pkgver()` function was introduced (see [here](https://github.com/pacstall/pacstall/releases) for info), so can we add that function to the `-git` pacscripts to enable auto updates?

**Describe the solution you'd like**
Use the `pkgver()` function to enable auto updates in `-git` pacscripts

**Describe alternatives you've considered**
None

**Additional context**
The pacscripts refered in this context are of these teams:
@pacstall/bashtop-git 
@pacstall/blang-git 
@pacstall/bpytop-git 
@pacstall/lemonbar-xft-git 
@pacstall/notion-git 
~@pacstall/pipewire-git~
@pacstall/st-distrotube 
~@pacstall/st-lukesmith~
@pacstall/tuner-git

### PR DESCRIPTION
**Pull request by wizard-28**
Use the new Pacstall 1.3 "Amaranth" pkgver() function to fetch the upstream version.

This aims to fix #12

### CODE REVIEW

**Comment by wizard-28** [comment]
The teams whose code I am changing are:
@pacstall/bashtop-git 
@pacstall/blang-git
@pacstall/bpytop-git
@pacstall/notion-git
@pacstall/st-distrotube
@pacstall/tuner-git

**Review by Henryws — APPROVED** [review]
looks good

**Review by louis77 — APPROVED** [review]

**Review by WRM-42 — APPROVED** [review]

**Comment by wizard-28** [comment]
@edward-riley @Ganesha2282882 need to review it..

**Comment by wizard-28** [comment]
@Henryws Should I merge this? Its been 5 days since the review was requested but @edward-riley, and @Ganesha2282882 haven't reviewed it yet.

**Comment by Henryws** [comment]
yeah

**Pull request merged**
