### PR TITLE
[test] Add shebang to the pacscripts I maintain

### PR DESCRIPTION
**Pull request by wizard-28**
This adds shebangs to my pacscripts

### CODE REVIEW

**Comment by Henryws** [comment]
Why?

**Comment by wizard-28** [comment]
CodeFactor can't check for errors if the file has no `.sh` extension

So I saw this issue, and it said that they have added checks for shebang, so I am testing my scripts with shebang to see whether code factor picks it up

https://github.com/codefactor-io/codefactor/issues/2#issuecomment-623287639

**Comment by Henryws** [comment]
I think that the ci we use is fine to check the script and pacscripts have a standardized format that's so simple, there's no way someone's could mess it up

**Comment by wizard-28** [comment]
The current CI is broken, it doesn't even execute properly for most of the pacscripts xD

**Comment by Henryws** [comment]
It does, but only on one's where people submit a single package per pr

**Comment by wizard-28** [comment]
Umm, looks like CF isn't detecting the file based on the shebang, well closing this PR

**Comment by wizard-28** [comment]
> It does, but only on one's where people submit a single package per pr

It doesn't when the pacscript uses `replace`

**Pull request closed without merging**
