### PR TITLE
add: `hyfetch`

### PR DESCRIPTION
**Pull request by spaceguybob**

### CODE REVIEW

**Comment by Elsie19** [comment]
```py
Traceback (most recent call last):
  File "/tmp/pacstall/hyfetch-1.4.10/./setup.py", line 4, in <module>
    from setuptools import setup, find_namespace_packages
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by spaceguybob** [comment]
> ```python
> Traceback (most recent call last):
>   File "/tmp/pacstall/hyfetch-1.4.10/./setup.py", line 4, in <module>
>     from setuptools import setup, find_namespace_packages
> ModuleNotFoundError: No module named 'setuptools'
> ```

what does thus mean?

**Comment by Elsie19** [comment]
Add `python3-setuptools` to the makedepends.

**Comment by Elsie19** [comment]
```python
Traceback (most recent call last):
  File "/tmp/pacstall/hyfetch-1.4.10/./setup.py", line 6, in <module>
    from hyfetch.__version__ import VERSION
  File "/tmp/pacstall/hyfetch-1.4.10/hyfetch/__init__.py", line 3, in <module>
    from . import main, constants
  File "/tmp/pacstall/hyfetch-1.4.10/hyfetch/main.py", line 12, in <module>
    from . import termenv, neofetch_util, pride_month
  File "/tmp/pacstall/hyfetch-1.4.10/hyfetch/termenv.py", line 7, in <module>
    from .color_util import RGB, AnsiMode
  File "/tmp/pacstall/hyfetch-1.4.10/hyfetch/color_util.py", line 6, in <module>
    from .constants import GLOBAL_CFG
  File "/tmp/pacstall/hyfetch-1.4.10/hyfetch/constants.py", line 8, in <module>
    from .types import LightDark
  File "/tmp/pacstall/hyfetch-1.4.10/hyfetch/types.py", line 1, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```

**Pull request closed without merging**
