### PR TITLE
upd(element-desktop-deb): `1.9.9` -> `1.10.4`

### PR DESCRIPTION
**Pull request by cat-master21**
Apparently there were already newer versions when I created this!

### CODE REVIEW

**Comment by cat-master21** [comment]
Also pre-commit.ci is messing with patch file annoyingly

**Comment by wizard-28** [comment]
Umm... @cat-master21 I need to force push, why have you disabled "Allow edits by maintainers" checkbox?

**Comment by cat-master21** [comment]
Pre-commit.ci will auto-commit which messes with my patch file as seem in previous commit. I did not even edit the patch file but pre-commit.ci still messes with it!

**Comment by Henryws** [comment]
> Pre-commit.ci will auto-commit which messes with my patch file as seem in previous commit. I did not even edit the patch file but pre-commit.ci still messes with it!

We made a PR (#781) that fixes this issue

**Comment by cat-master21** [comment]
So then what is this commit: https://github.com/pacstall/pacstall-programs/pull/779/commits/9932a9051fd06c743a1f47c745cf7afaf7cedec6 that messes with patch file?

**Comment by cat-master21** [comment]
Ready for merge @wizard-28.

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
