### PR TITLE
add: `com.github.mirkobrombin.bottles-deb`

### PR DESCRIPTION
**Pull request by cat-master21**

### CODE REVIEW

**Comment by wizard-28** [comment]
I'll let @Henryws handle this.

**Review by Henryws — APPROVED** [review]

**Comment by wizard-28** [comment]
@Henryws why are we doing this? Why is the name so long?

**Comment by Henryws** [comment]
> @Henryws why are we doing this? Why is the name so long?

It's complicated (https://discord.com/channels/839818021207801878/866673569521991700/955247094111830060).

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Add `repology` if you want.

**Comment by cat-master21** [comment]
@wizard-28 there isn't a repology for bottles-v1 (under as com.github.mirkobrombin.bottles).

**Review by wizard-28 — COMMENTED** [review]
Yeah seeing your version string, I think this is a continuous release that their CI releases, so it doesn't have a well defined "version".

Can you switch the `url` to a static release or something? Which has a well defined `version`.

Also `bottles` is on [Repology](https://repology.org/project/bottles/versions)

**Comment by cat-master21** [comment]
@wizard-28 `bottles-v1` is not on Repology. Also becuase there isn't another way to do things, refresh (update/+1) the version for a newer checksum.

**Comment by wizard-28** [comment]
> @wizard-28 `bottles-v1` is not on Repology. Also becuase there isn't another way to do things, refresh (update/+1) the version for a newer checksum.

Okay.

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
