### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by raxod502**
This is a draft PR for testing that the change detection on https://github.com/pacstall/pacstall-programs/pull/894 is working correctly.

### CODE REVIEW

**Comment by Henryws** [comment]
Try with a different package.

**Comment by Henryws** [comment]
Try something small, like `hyperfine-bin`

**Comment by raxod502** [comment]
I tried with the latest package that was merged to master, on the principle that CI probably hasn't broken for it yet :)

**Comment by Henryws** [comment]
Ok, can you remove the testing comments

**Comment by raxod502** [comment]
This PR isn't for merging, it's just for testing :)
For review, you want to be looking at https://github.com/pacstall/pacstall-programs/pull/894.

**Pull request closed without merging**
