### PR TITLE
upd(opera-deb): `82.0.4227.43` -> `84.0.4316.42`

### PR DESCRIPTION
**Pull request by WRM-42**

### CODE REVIEW

**Review by wizard-28 — COMMENTED** [review]
@WRM-42 do you want to use https://github.com/pacstall/pacup (https://github.com/pacstall/pacstall-programs/discussions/845)?

**Comment by WRM-42** [comment]
The deb version of Opera is not on Repology

**Comment by wizard-28** [comment]
> The deb version of Opera is not on Repology

Hmm... It's there? https://repology.org/project/opera/versions

You don't need to search for the deb version, just searching for the project would work.

**Review by wizard-28 — COMMENTED** [review]
This is again outdated, so updating it using Pacup

**Review by wizard-28 — APPROVED** [review]

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
