### PR TITLE
add: smplayer-deb

### PR DESCRIPTION
**Pull request by pure-cheekbones**

### CODE REVIEW

**Review by Henryws — CHANGES_REQUESTED** [review]
Update the `packagelist`

https://github.com/pacstall/pacstall-programs/blob/master/make-a-pacscript.md#updating-the-packagelist

**Comment by pure-cheekbones** [comment]
updated `packagelist` https://github.com/pacstall/pacstall-programs/pull/611/commits/3de42f1b5390aa3eec12d224be573894415660cd

**Comment by Henryws** [comment]
Can you amend your commit to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)?

`git commit --amend -m 'upd(smplayer-bin): packagelist' && git push -f`

**Comment by pure-cheekbones** [comment]
my bad, will fix now

**Comment by Henryws** [comment]
If you need help in any way, you can visit our Discord server for help: https://discord.gg/yzrjXJV6K8

Just in case you need it 😉

**Comment by pure-cheekbones** [comment]
all good now?

**Comment by Henryws** [comment]
Testing it right now!

**Review by Henryws — APPROVED** [review]
LGTM!!

**Pull request merged**
