### PR TITLE
Update Micro

### PR DESCRIPTION
**Pull request by IntoTheVoid-900**

### CODE REVIEW

**Comment by Henryws** [comment]
Fix PR name

**Review by Henryws — CHANGES_REQUESTED** [review]
Update `hash` as well.

**Comment by IntoTheVoid-900** [comment]
Sorry, I do not know the formatting for these PRs. I just noticed that micro was a few months outdated, and wanted to try to update it.

**Comment by Henryws** [comment]
That's fine! I should add that information to the wiki. I'll do it later.

**Comment by IntoTheVoid-900** [comment]
Thank you for updating it. The info would be helpful.

**Pull request closed without merging**
