### PR TITLE
fix(obs-backgroundremoval-git): fix build scripts

### PR DESCRIPTION
**Pull request by umireon**

### CODE REVIEW

**Review by Zahrun — CHANGES_REQUESTED** [review]

**Review by Zahrun — APPROVED** [review]
lgtm @Elsie19

**Comment by Elsie19** [comment]
All the checks failed. Merge in from master

**Comment by umireon** [comment]
I don't know why the uninstalling test fails. Does this test need to be passed?

**Comment by Zahrun** [comment]
> I don't know why the uninstalling test fails. Does this test need to be passed?

This is only a CI issue due to the cmake-deb pacdep. We should be good to merge.

**Review by Elsie19 — APPROVED** [review]

**Pull request merged**
