### PR TITLE
upd(freetube-deb): `0.21.3` -> `0.22.0`

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Comment by archisman-panigrahi** [comment]
@Zahrun New version released, 0.22.1

**Comment by Zahrun** [comment]
@archisman-panigrahi would you like to become maintainer for freetube-deb?

**Comment by archisman-panigrahi** [comment]
@Zahrun I will be happy to. 
Can you give me a brief tutorial? Is it as simple as updating version number and SHA sums just like how AUR works?

**Comment by Zahrun** [comment]
Make sure to read https://github.com/pacstall/pacstall-programs/blob/master/README.md 
Set up your environment with the hooks as per https://github.com/pacstall/pacstall-programs/blob/master/README.md#how-to-setup-the-environment-for-pacscript-development
Then it is just updating the file at packages/freetube-deb/freetube-deb.pacscript
Field pkgver and sha256sums, and you can replace maintainer as well
Make sure to name your commit in the same exact format as upd(freetube-deb): \`0.21.3\` -> \`0.22.0\`
When you commit, the hooks will automatically adjust srclist and packages/freetube-deb/.SRCINFO accordingly

If you have any doubt, you can consult the wiki https://github.com/pacstall/pacstall/wiki/Pacscript-101 or ask me :)

You can also check https://github.com/pacstall/pacup which is a tool to automate parts of the process of updating a package.

**Comment by archisman-panigrahi** [comment]
@Zahrun Please check https://github.com/pacstall/pacstall-programs/pull/7117.
I am a regular user of freetube, so I would know when there is a new update. Sorry about the delay. Now that I have figured out how to update the pacscript, it should not take much time.

**Comment by Zahrun** [comment]
Super, thank you for becoming the maintainer

**Pull request merged**
