### PR TITLE
fix(unicorn-{desktop,mobile}-git): add dynamic workspaces 

### PR DESCRIPTION
**Pull request by ajstrongdev**
This pacscript update will bump dynamic workspaces from Stampede (testing) into the Unicorn pacscript as a pacdep

### CODE REVIEW

**Review by Elsie19 — CHANGES_REQUESTED** [review]
Bump pkgrel or pkgver for each of the packages you updated.

**Comment by oklopfer** [comment]
https://github.com/pacstall/pacstall-programs/blob/master/packages/xfce4-dynamic-workspaces-plugin-git/xfce4-dynamic-workspaces-plugin-git.pacscript

looks like this needs to be updated to be a cp instead of ln

**Comment by Elsie19** [comment]
@ajstrongdev there are now merge conflicts so please fix those.

**Comment by ajstrongdev** [comment]
Resolved

**Comment by oklopfer** [comment]
> Resolved

No not resolved you dropped a dep

**Comment by ajstrongdev** [comment]
> > Resolved
> 
> No not resolved you dropped a dep

Oops, fixed now.

**Comment by oklopfer** [comment]
Both packages should have a pkgrel bump from this. Also be sure to add to unicorn-mobile too and not just desktop.

**Review by oklopfer — CHANGES_REQUESTED** [review]
See above

**Pull request merged**
