### PR TITLE
upd(ulauncher-deb): `5.15.6` -> `6.0.0~beta5`

### PR DESCRIPTION
**Pull request by oklopfer**
breaks unicorns keybinds :/ but much quicker and more robust so we just have to update them
Screenshot 2024-01-24 at 3 39 10 PM

### CODE REVIEW

**Comment by Elsie19** [comment]
Why is this still a draft?

**Comment by oklopfer** [comment]
> Why is this still a draft?

it breaks the unicorn keybind

**Comment by oklopfer** [comment]
bruh it still broke on noble

**Comment by oklopfer** [comment]
fix for unicorn-desktop-git/mobile-git:
add these to post_install
1. `xfconf-query -c xfce4-keyboard-shortcuts -n -t 'string' -p '/commands/custom/<Super>s' 2&>1 /dev/null || xfconf-query -c xfce4-keyboard-shortcuts -n -t 'string' -p '/commands/custom/<Super>s' -s 'gapplication launch io.ulauncher.Ulauncher'`
2. `systemctl --user enable ulauncher --now`

add to post_remove
1. `systemctl --user disable ulauncher`

we should also add `<property name="&lt;Super&gt;s" type="string" value="gapplication launch io.ulauncher.Ulauncher"/>` in unicorn under https://github.com/rhino-linux/unicorn/blob/10d0da119aca6d4fd7b5d1185db87a3cb3de088f/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml#L162 (as well as in failsafe)

**Pull request merged**
