### PR TITLE
add: `ripgrep-deb`

### PR DESCRIPTION
**Pull request by jerengie**
This PR adds a package for ripgrep. The `.deb` comes from the upstream repo of `ripgrep`.

### CODE REVIEW

**Comment by Elsie19** [comment]
Is ripgrep in the apt repos? If so, what's the version on Jammy?

**Comment by jerengie** [comment]
> Is ripgrep in the apt repos? If so, what's the version on Jammy?

Yes, it's in the repos. The version on Jammy is 13.0.0.

**Comment by Elsie19** [comment]
> > Is ripgrep in the apt repos? If so, what's the version on Jammy?
> 
> Yes, it's in the repos. The version on Jammy is 13.0.0.

Ok because here's my problem: I don't want packages that exist at a reasonable version in the repos to be added to pacstall. Basically I don't want pacstall to serve as an updated Ubuntu repo.

**Comment by vigress8** [comment]
> Ok because here's my problem: I don't want packages that exist at a reasonable version in the repos to be added to pacstall. Basically I don't want pacstall to serve as an updated Ubuntu repo.

Why?

**Comment by Elsie19** [comment]
> > Ok because here's my problem: I don't want packages that exist at a reasonable version in the repos to be added to pacstall. Basically I don't want pacstall to serve as an updated Ubuntu repo.
> 
> Why?

Sorry what I meant is an updated Ubuntu repo where it's full of packages that are slightly ahead of the Ubuntu repos, if that makes any sense 😆

**Comment by jerengie** [comment]
From my point of view, this is perfectly understandable. Shall I close this PR then?

**Pull request closed without merging**
