### PR TITLE
upd(kvantum): `0.19.0` -> `1.0.0`

### PR DESCRIPTION
**Pull request by cat-master21**

### CODE REVIEW

**Comment by Henryws** [comment]
Double check the CI install for the missing dependencies

**Comment by cat-master21** [comment]
It appears this issue has to do with Pacstall possibly:
Screenshot from 2022-02-03 17-37-32

**Comment by Henryws** [comment]
Does kvantum install properly on your machine?

**Comment by cat-master21** [comment]
same issue on my system:
Screenshot from 2022-02-03 17-51-37
manually installing dependencies works then installing package:
Screenshot from 2022-02-03 17-55-16

**Comment by Henryws** [comment]
Can you send the exact commands you ran to install the dependencies?

**Comment by cat-master21** [comment]
Downloaded kvantum.pacstall with Firefox 96.0.3 (64-bit) on Ubuntu Focal LTS to my home directory. Opened up Gnome Terminal and did `pacstall -Il kvantum`. Choose to remove dependencies after installation which may not be issue considering install-package choose to not remove them but still got same error. Anyway next dpkg ran into that issue but still continued to install until make couldn't find qt5 which finally stopped the installation. Installing the packages with apt then doing `pacstall -Il kvantum` worked like normal.

**Comment by wizard-28** [comment]
@Henryws, What to do here?

**Comment by Henryws** [comment]
Can you test it again, but this time run `pacstall -U Henryws bugfix/dpkg_deps` beforehand

**Comment by cat-master21** [comment]
Running same commands after `pacstall -U pacstall develop` fixes the issue. Pacstall doesn't give me a prompt to install dependencies however.

**Comment by Henryws** [comment]
Did you test it in a fresh VM?

**Comment by cat-master21** [comment]
No, on previous VM with Kvantum, and dependencies all removed.

**Review by Henryws — APPROVED** [review]

**Review by wizard-28 — APPROVED** [review]
The dependencies install correctly.

**Pull request merged**
