### PR TITLE
upd(hypnotix-deb): `3.1` -> `3.2`

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Review by wizard-28 — CHANGES_REQUESTED** [review]
CI fails

**Comment by Zahrun** [comment]
Testing and Unstable don’t have libmpv1, they have libmpv2. Can I unpack the deb, modify the dependency and repack the deb in `prepare()`?

For stable, https://github.com/pacstall/pacstall-programs/pull/2218 is required

**Comment by Henryws** [comment]
> Testing and Unstable don’t have libmpv1, they have libmpv2. Can I unpack the deb, modify the dependency and repack the deb in `prepare()`?
> 
> For stable, #2220 is required

No, the package is installed as-is. What you *could* do is create a github repo and upload a modified Deb.

**Comment by Zahrun** [comment]
It seems the incompatible variable is not taken into account. Did I mistype something?

**Comment by Henryws** [comment]
No, I'll check it out later

**Comment by Henryws** [comment]
Yeah I'm not sure.

**Comment by Zahrun** [comment]
Coded as sid in pacstall https://github.com/pacstall/pacstall/blob/develop/misc/scripts/install-local.sh#L165

**Comment by Henryws** [comment]
Are you ok with having testing and unstable not work?

**Review by Henryws — APPROVED** [review]

**Pull request merged**
