### PR TITLE
Fix issues with `conky-manager`

### PR DESCRIPTION
**Pull request by ty1118**

### CODE REVIEW

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Can you switch `version` to `pkgver()`? So that it gets updated dynamically in the future?

```bash
pkgver () {
  git ls-remote <url> <branch> | cut -f1 # Returns the latest commit hash from remote
}
version="$(pkgver)"
```

Look [here](https://github.com/pacstall/pacstall-programs/blob/master/packages/awesome-git/awesome-git.pacscript) for an example.

**Review by wizard-28 — DISMISSED** [review]
And rename this script to `conky-manager2-git`.

**Comment by NarutoXY** [comment]
Just update this script. `conky-manager2` will create confusion

**Comment by wizard-28** [comment]
> Just update this script. `conky-manager2` will create confusion

This [conky-manager2](https://github.com/zcot/conky-manager2) is actually a fork of [conky-manager](https://github.com/teejee2008/conky-manager). So I think renaming it to `conky-manager2-git`(`-git` suffix as this is a git pacscript) will **prevent** confusion in the future.

**Comment by wizard-28** [comment]
> Or do something like `conky-manager-ty1118`

Unnecessarily long.

**Comment by NarutoXY** [comment]
> This conky-manager2 is actually a fork of conky-manager. So I think renaming it to conky-manager2-git(-git suffix as this is a git pacscript) will prevent confusion in the future

Ohk sounds good

> > Or do something like `conky-manager-ty1118`
> 
> Unnecessarily long, and why `-ty1118`? The fork maintainer is `zcot`.

`zcot` is maintainer of fork. But on pacstall programs repo `ty1118` is maintainer of the pacscript. Leave this thing.

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Can you switch `version` to `pkgver()`? So that it gets updated automatically in the future?

```bash
pkgver () {
  git ls-remote <url> <branch> | cut -f1 # Returns the latest commit hash from remote
}
version="$(pkgver)"
```

Look [here](https://github.com/pacstall/pacstall-programs/blob/master/packages/awesome-git/awesome-git.pacscript) for an example.

---

Change this pacscript name to `conky-manager-zcot-git` (Don't forget to update the `packagelist` too)

**Comment by Henryws** [comment]
@wizard-28 is this ready to merge?

**Comment by wizard-28** [comment]
> @wizard-28 is this ready to merge?

No... I've requested changes. @ty1118 is expected to resolve them.

**Comment by NarutoXY** [comment]
Welp I created PR to the fork of ty1118, now he can merge it in his fork and then we can merge this PR. For some reason, it says I do not have write access to the fork (but I literally committed a minute ago in that fork.)

**Comment by NarutoXY** [comment]
Fixed all requests in #273

**Pull request closed without merging**
