### PR TITLE
ci(tests.yml): switch ubuntu sources to deb-822 format

### PR DESCRIPTION
**Pull request by oklopfer**

### CODE REVIEW

**Review by Elsie19 — DISMISSED** [review]
Haven't tested haven't viewed code lgtm 🚀

**Comment by oklopfer** [comment]
> Haven't tested haven't viewed code lgtm 🚀

not sure it works yet

**Review by Elsie19 — CHANGES_REQUESTED** [review]
Fix things you mentioned 😁

**Comment by oklopfer** [comment]
> Haven't tested haven't viewed code lgtm 🚀

ok yup it wokrs

**Pull request merged**
