### PR TITLE
[Update Package] Add licenses and style changes

### PR DESCRIPTION
**Pull request by wizard-28**
This addresses my pacscripts affected my #36.

Also, it updates the style of my pacscripts.

### CODE REVIEW

**Comment by Henryws** [comment]
Looks good

**Comment by wizard-28** [comment]
This isn't ready for review, why did you forcefully make it?

**Comment by wizard-28** [comment]
Don't review until I have marked it ready for review.

**Comment by Henryws** [comment]
> Don't review until I have marked it ready for review.

Oh, I didn't see it on mobile

**Comment by wizard-28** [comment]
Okay review it now.

You may want to review this PR carefully, things may be broken (mostly I couldn't check because the CI is broken)

**Review by Henryws — APPROVED** [review]
Looks good

**Pull request merged**
