### PR TITLE
fix(tenacity-git): build failures

### PR DESCRIPTION
**Pull request by echometerain**

### CODE REVIEW

**Comment by echometerain** [comment]
the ci can't find `libportsmf0v5` but my apt can and it builds

**Comment by Henryws** [comment]
> the ci can't find `libportsmf0v5` but my apt can and it builds

Is it because it's not available on certain distros?

**Comment by echometerain** [comment]
it's available on ubuntu & popos
image

**Comment by Mar0xy** [comment]
It isn't available in debian at all only on ubuntu (and obv it's derivates)

**Comment by Henryws** [comment]
Merging as it works on Ubuntu.

**Review by Henryws — APPROVED** [review]

**Pull request merged**
