### PR TITLE
upd(bitwig-studio-deb): `4.1.2` -> `4.2`

### PR DESCRIPTION
**Pull request by Zahrun**
udp(bitwig-studio-deb): `4.1.2` -> `4.2`

### CODE REVIEW

**Comment by wizard-28** [comment]
@Zahrun do you want to connect this pacscript with repology and thus use Pacup?

**Comment by wizard-28** [comment]
> @Zahrun do you want to connect this pacscript with repology and thus use Pacup?

2 days have passed so I assume that's a no then.

**Comment by wizard-28** [comment]
@Henryws `i386` error.

**Review by Henryws — APPROVED** [review]
Works when I run `dpkg --add-architecture i386 ; sudo apt update`, then install the pacscript. The CI will be fixed later.

**Pull request merged**
