### PR TITLE
upd(virtualbox-deb): `0.7.12` -> `0.7.14`

### PR DESCRIPTION
**Pull request by Xdavius**
add comment for latest_version
passed to incompatible (debian:*) : debian packages/repos exists (fasttrack)

### CODE REVIEW

**Comment by Elsie19** [comment]
Why is this only succeeding on 2 distros?

**Comment by oklopfer** [comment]
> Why is this only succeeding on 2 distros?

It's the latest version upstream in the other ones; this is a backport

**Comment by Xdavius** [comment]
> Why is this only succeeding on 2 distros?

package splited for all distros now with new deps names etc...

will work on a -repo package. will be better and could set several distros.

this -deb is ok for what it is made for.

**Comment by Elsie19** [comment]
Ok well make the appropriate `incompatible` changes.

**Comment by Xdavius** [comment]
> Ok well make the appropriate `incompatible` changes.

I have already added incompatible=(debian:*)

Not sure for ubuntu...

**Comment by oklopfer** [comment]
> > Ok well make the appropriate `incompatible` changes.
> 
> I have already added incompatible=(debian:*)
> 
> Not sure for ubuntu...

incompatible=("debian:*" "ubuntu:mantic" "ubuntu:noble" "ubuntu:devel")

**Pull request merged**
