### PR TITLE
chan(*): migrate to `source` and `hash` arrays

### PR DESCRIPTION
**Pull request by vigress8**
In preparation for pacstall/pacstall#1038

### CODE REVIEW

**Comment by Elsie19** [comment]
Send the commands you used to convert these files.

**Comment by Elsie19** [comment]
```py
#!/usr/bin/env python3

import re

def subst(file, search_p, replace_p):
    with open(file, 'r') as f:
        contents = f.readlines()

    with open(file, 'w') as f:
        for line in contents:
            line = re.sub(search_p, replace_p, line)
            f.write(line)


def delete_block(file, begin, end):
    with open(file, 'r') as f:
        contents = f.readlines()

    begin_index = None
    end_index = None
    for index, line in enumerate(contents):
        if re.search(begin, line):
            begin_index = index
        if re.search(end, line):
            end_index = index
            break

    if begin_index is not None and end_index is not None:
        del contents[begin_index : end_index + 1]
    with open(file, 'w') as f:
        f.writelines(contents)


with open("packagelist", 'r') as plist:
    for pname in plist:
        p = pname.rstrip()
        ppath = f"packages/{p}/{p}.pacscript"
        if re.search('-git', p):
            delete_block(ppath, r'^pkgver\(\)', '^}')
            subst(ppath, r'url="https(.*)(?<!\.git)"', r'url="git+https\1"')

        subst(ppath, r'url=(.*)', r'source=(\1)')
        subst(ppath, r'hash=(.*)', r'hash=(\1)')
```

**Comment by oklopfer** [comment]
> ```python
> #!/usr/bin/env python3
> 
> import re
> 
> def subst(file, search_p, replace_p):
>     with open(file, 'r') as f:
>         contents = f.readlines()
> 
>     with open(file, 'w') as f:
>         for line in contents:
>             line = re.sub(search_p, replace_p, line)
>             f.write(line)
> 
> 
> def delete_block(file, begin, end):
>     with open(file, 'r') as f:
>         contents = f.readlines()
> 
>     begin_index = None
>     end_index = None
>     for index, line in enumerate(contents):
>         if re.search(begin, line):
>             begin_index = index
>         if re.search(end, line):
>             end_index = index
>             break
> 
>     if begin_index is not None and end_index is not None:
>         del contents[begin_index : end_index + 1]
>     with open(file, 'w') as f:
>         f.writelines(contents)
> 
> 
> with open("packagelist", 'r') as plist:
>     for pname in plist:
>         p = pname.rstrip()
>         ppath = f"packages/{p}/{p}.pacscript"
>         if re.search('-git', p):
>             delete_block(ppath, r'^pkgver\(\)', '^}')
>             subst(ppath, r'url="https(.*)(?<!\.git)"', r'url="git+https\1"')
> 
>         subst(ppath, r'url=(.*)', r'source=(\1)')
>         subst(ppath, r'hash=(.*)', r'hash=(\1)')
> ```

unnecessary, kill it with fire
```bash
packagelist="packagelist"
while IFS= read -r package_name; do
    pacscript_path="packages/${package_name}/${package_name}.pacscript"
    if [[ "$package_name" == *-git ]]; then
        if ! grep -q 'url=".*\.git"$' "$pacscript_path"; then
            sed -i '' 's|url="https://|url="git+https://|' "$pacscript_path"
        fi
        sed -i '' '/^pkgver() {/,/^}/d' "$pacscript_path"
    fi
    sed -i '' '/^url=/{s|^url="|source=("|; s|"$|")|;}' "${pacscript_path}"
    sed -i '' '/^hash=/{s|^hash="|hash=("|; s|"$|")|;}' "${pacscript_path}"
done < "$packagelist"
```

**Comment by vigress8** [comment]
Shorter doesn't equal better, when it's much less readable

**Comment by oklopfer** [comment]
> Shorter doesn't equal better, when it's much less readable

No, but faster does
```bash
$ time python3 convert.py
python3 convert.py  0.05s user 0.09s system 76% cpu 0.188 total
$ time ./convert.sh 
./convert.sh  0.38s user 1.20s system 84% cpu 1.877 total
```

you're lucky it's faster...

**Pull request closed without merging**
