### PR TITLE
upd(epson-printer-utility-deb): added repology

### PR DESCRIPTION
**Pull request by Zahrun**

### CODE REVIEW

**Review by Henryws — CHANGES_REQUESTED** [review]
CI fails

**Comment by Zahrun** [comment]
> CI fails

As soon as debian unstable develop fails, the other jobs stopped `The job was canceled because "debian_unstable_develop" failed.`
This pacscript has dependencies that I was only able to find in a ppa, hence it will not work on debian.

**Comment by Henryws** [comment]
What to do @wizard-28

**Comment by cat-master21** [comment]
The Debian alt is https://packages.debian.org/sid/lsb-compat though amd64 version is for stretch only. Debian has indeed removed it though except for base packages https://wiki.debian.org/DebianLsb

**Comment by wizard-28** [comment]
> What to do @wizard-28

So is there any way to fix the issue on Debian? Does it work with the base package in Debian as @cat-master21 pointed out?

If not, then disable it's installation on Debian and call it a day.

**Comment by cat-master21** [comment]
The debian alternative is `lsb-compat` https://packages.debian.org/stretch/amd64/lsb-compat/filelist and https://packages.ubuntu.com/jammy/amd64/lsb-core/filelist note that lsb is just a meta package that installs this and also `lsb-printing` https://packages.ubuntu.com/jammy/lsb-printing which is yet another meta package. It is probably one of those dependencies that this deb actually needs. Also see https://wiki.debian.org/DebianLsb for more info.

**Pull request closed without merging**
