### PR TITLE
add brave-browser-deb

### PR DESCRIPTION
**Pull request by Zahrun**
and cleaned commit history

### CODE REVIEW

**Review by D-Brox — CHANGES_REQUESTED** [review]
Add packages to packagelist

**Review by wizard-28 — COMMENTED** [review]
Can you explain again why this `release` edition needs a separate key ring whereas the `beta` and `nightly` don't need one?

**Comment by Zahrun** [comment]
> Can you explain again why this `release` edition needs a separate key ring whereas the `beta` and `nightly` don't need one?

It is there in the official deb dependency list for the release version only (see [Brave Issue 5111](https://github.com/brave/brave-browser/issues/5111)).

**Review by D-Brox — APPROVED** [review]

**Review by wizard-28 — APPROVED** [review]

**Review by Henryws — APPROVED** [review]

**Comment by wizard-28** [comment]
Well, this happened:
```
[+] INFO: Installing brave-keyring-deb
[*] WARNING: Prompts are disabled
[*] WARNING: There is no package with the name brave-keyring-deb
```

**Comment by Henryws** [comment]
Did you add his repo?

**Comment by wizard-28** [comment]
> Did you add his repo?

Oh... Yeah it should work on merge... My bad.

**Comment by Henryws** [comment]
> > Did you add his repo?
> 
> Oh... Yeah it should work on merge... My bad.

Or you could have just used the `-A` flag...

**Comment by wizard-28** [comment]
> > > Did you add his repo?
> > 
> > 
> > Oh... Yeah it should work on merge... My bad.
> 
> Or you could have just used the `-A` flag...

I couldn't have tested it anyways... No space left on device.

**Pull request merged**
