### PR TITLE
add: `xfce4-deb`

### PR DESCRIPTION
**Pull request by httpllamaz**
- Add: xfce4
- upd: packagelist with xfce4
- upd: Linux kernel add: xfce4-deb

---
name: xfce4-deb, linux*
about: Adds xfce4-deb to Pacstall & Update Linux kernel packages
labels: Package Add, Package Update
assignees: @wizard-28 @henryws

---

### CODE REVIEW

**Comment by Henryws** [comment]
Fix the PR title.

**Comment by httpllamaz** [comment]
> Fix the PR title.

What does it need changing to?

**Comment by Henryws** [comment]
add: `xfce4-deb` probably.

**Comment by httpllamaz** [comment]
Done

**Review by Henryws — APPROVED** [review]

**Pull request merged**
