### PR TITLE
Shorten hashes for -git packages

### PR DESCRIPTION
**Pull request by Mar0xy**
Repology when

### CODE REVIEW

**Comment by Mar0xy** [comment]
Well that worked better than expected :rofl:

**Comment by Mar0xy** [comment]
image
image

**Review by Henryws — CHANGES_REQUESTED** [review]
I believe you can use cut to extract a substring. Don't use awk, it's too big for a simple extraction

**Comment by Mar0xy** [comment]
> I believe you can use cut to extract a substring. Don't use awk, it's too big for a simple extraction

You can but then you would need to set another pipe just to substring it via cut since you can't do multiple arguments in the same command

**Comment by Mar0xy** [comment]
There that is how the situation would be when using cut.

**Comment by Mar0xy** [comment]
@Henryws If you are fine with this solution of using cut I could change all git packages which currently use this method in a PR to make them use 8 char long hashes.

**Comment by Henryws** [comment]
Yeah using two instances of `cut` will be faster than calling `awk`

**Review by Henryws — APPROVED** [review]

**Pull request merged**
