### PR TITLE
upd(armcord-deb): `3.2.6` -> `3.2.7`

### PR DESCRIPTION
**Pull request by jgr-io**
Update armcord pacscript

### CODE REVIEW

**Comment by Elsie19** [comment]
Fix the title to conform to our standards, as explained in [our docs](https://github.com/pacstall/pacstall/wiki/Submitting-a-Pacscript#how-to-create-a-valid-pr). You can also look at [past PRs](https://github.com/pacstall/pacstall-programs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3A%22Update+Package%22) to get an idea of how to format the title if you're unsure.

---

<sub>This is a saved reply I have set up, so don't worry, I don't sound this generic IRL 😆</sub>

**Comment by vigress8** [comment]
You need to update sha256sums as well

**Comment by jgr-io** [comment]
My apologies, will do

**Comment by jgr-io** [comment]
How do I check those? I've never had to do this sort of stuff

**Comment by fang64** [comment]
> How do I check those? I've never had to do this sort of stuff

@jgr-io 
You can use the sha256sum command of the file you are intending to download in the pacscript.
for example
`
wget "https://github.com/ArmCord/ArmCord/releases/download/v3.2.7/ArmCord_3.2.7_amd64.deb" -O /tmp/ArmCord_3.2.7_amd64.deb
sha256sum /tmp/ArmCord_3.2.7_amd64.deb
`
you will get a hash output and be able to change it in your pacscript

**Comment by jgr-io** [comment]
I've fixed the amd64 hash, will try and do the same for the arm64 hash

**Comment by jgr-io** [comment]
Done and done, anything else?

**Review by oklopfer — APPROVED** [review]

**Pull request merged**
