### PR TITLE
upd(treefetch-bin): `1.2.1` -> `2.0.0`

### PR DESCRIPTION
**Pull request by angelofallars**

### CODE REVIEW

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Update `hash`

**Comment by angelofallars** [comment]
> Update `hash`

How do I do that? What command/program should I use on the binary to generate a new hash?

**Comment by wizard-28** [comment]
> > Update `hash`
> 
> How do I do that? What command/program should I use on the binary to generate a new hash?

`sha256sum <file>`

**Comment by angelofallars** [comment]
Done 3e99f669351dcd16cc80c7f80a92466e286430ca

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
