### PR TITLE
upd(bat): `0.19.0` -> `0.21.0`

### PR DESCRIPTION
**Pull request by cat-master21**

### CODE REVIEW

**Review by Henryws — CHANGES_REQUESTED** [review]
review the CI logs, and fix the cargo error.

**Comment by cat-master21** [comment]
This fails on debian stable because it has a outdated rust see https://github.com/pacstall/pacstall-programs/runs/7504050314?check_suite_focus=true that shows it works on Ubuntu. @Henryws

**Comment by Henryws** [comment]
@wizard-28 what to do..?

**Comment by Henryws** [comment]
I'll merge this as it works on Ubuntu.

**Pull request merged**
