### PR TITLE
fix & upd(freetube-deb): `0.17.1` -> `0.18.0`

### PR DESCRIPTION
**Pull request by soumyatheman**
Added Repology info for easy update, and updated it to latest beta 0.18.0

### CODE REVIEW

**Review by wizard-28 — APPROVED** [review]

**Comment by wizard-28** [comment]
@WRM-42, Do you wish to keep maintaining this pacscript?

**Comment by soumyatheman** [comment]
> @WRM-42, Do you wish to keep maintaining this pacscript?

Not now, may be later

**Comment by Henryws** [comment]
Wizard was asking WRM..

**Comment by soumyatheman** [comment]
> Wizard was asking WRM..

LOL! Noob me

**Review by wizard-28 — APPROVED** [review]

**Comment by wizard-28** [comment]
Merging it for now, @WRM-42 can respond later.

**Pull request merged**
